"""initial NUMMF schema

Revision ID: 0001
Revises:
Create Date: 2026-10-04 00:42:48.268908
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("event_id", sa.String(length=80), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=200), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("output_hash", sa.String(length=64), nullable=False),
        sa.Column("previous_event_hash", sa.String(length=64), nullable=False),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("event_hash"),
    )
    op.create_index(op.f("ix_audit_events_entity_id"), "audit_events", ["entity_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_entity_type"), "audit_events", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_table(
        "canonical_materials",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("family", sa.String(length=100), nullable=False),
        sa.Column("generated_description", sa.Text(), nullable=False),
        sa.Column("attribute_signature", sa.Text(), nullable=False),
        sa.Column("template_version", sa.String(length=50), nullable=False),
        sa.Column("generation_method", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("taxonomy", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attribute_signature"),
    )
    op.create_index(
        op.f("ix_canonical_materials_family"), "canonical_materials", ["family"], unique=False
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("run_id", sa.String(length=80), nullable=False),
        sa.Column("dataset_version", sa.String(length=100), nullable=False),
        sa.Column("split_strategy", sa.String(length=200), nullable=False),
        sa.Column("label_source", sa.String(length=40), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "material_pairs",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("material_a", sa.String(length=80), nullable=False),
        sa.Column("material_b", sa.String(length=80), nullable=False),
        sa.Column("label_source", sa.String(length=32), nullable=False),
        sa.Column("relation", sa.String(length=60), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_material_pairs_material_a"), "material_pairs", ["material_a"], unique=False
    )
    op.create_index(
        op.f("ix_material_pairs_material_b"), "material_pairs", ["material_b"], unique=False
    )
    op.create_table(
        "model_versions",
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("model_type", sa.String(length=100), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "source_artifacts",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("source_system", sa.String(length=200), nullable=False),
        sa.Column("source_organization", sa.String(length=200), nullable=False),
        sa.Column("source_record_id", sa.String(length=200), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_document", sa.Text(), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_artifacts_source_system"),
        "source_artifacts",
        ["source_system"],
        unique=False,
    )
    op.create_table(
        "taxonomies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("taxonomy", sa.String(length=100), nullable=False),
        sa.Column("taxonomy_version", sa.String(length=50), nullable=False),
        sa.Column("taxonomy_code", sa.String(length=100), nullable=False),
        sa.Column("taxonomy_name", sa.Text(), nullable=False),
        sa.Column("parent_code", sa.String(length=100), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("hsn_sac_code", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_taxonomies_taxonomy"), "taxonomies", ["taxonomy"], unique=False)
    op.create_index(
        op.f("ix_taxonomies_taxonomy_code"), "taxonomies", ["taxonomy_code"], unique=False
    )
    op.create_table(
        "materials",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("source_artifact_id", sa.String(length=80), nullable=False),
        sa.Column("raw_description", sa.Text(), nullable=False),
        sa.Column("normalized_description", sa.Text(), nullable=False),
        sa.Column("material_code", sa.String(length=200), nullable=False),
        sa.Column("organization", sa.String(length=200), nullable=False),
        sa.Column("plant", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["source_artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_materials_material_code"), "materials", ["material_code"], unique=False
    )
    op.create_index(op.f("ix_materials_organization"), "materials", ["organization"], unique=False)
    op.create_index(
        op.f("ix_materials_source_artifact_id"), "materials", ["source_artifact_id"], unique=False
    )
    op.create_table(
        "nmc_registry",
        sa.Column("nmc", sa.String(length=100), nullable=False),
        sa.Column("canonical_material_id", sa.String(length=80), nullable=False),
        sa.Column("family", sa.String(length=100), nullable=False),
        sa.Column("attribute_signature", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_status", sa.String(length=32), nullable=False),
        sa.Column("human_override", sa.Boolean(), nullable=False),
        sa.Column("override_reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_material_id"],
            ["canonical_materials.id"],
        ),
        sa.PrimaryKeyConstraint("nmc"),
        sa.UniqueConstraint("attribute_signature"),
    )
    op.create_index(
        op.f("ix_nmc_registry_canonical_material_id"),
        "nmc_registry",
        ["canonical_material_id"],
        unique=False,
    )
    op.create_index(op.f("ix_nmc_registry_family"), "nmc_registry", ["family"], unique=False)
    op.create_table(
        "review_tasks",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("pair_id", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("assigned_to", sa.String(length=200), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("priority", sa.Float(), nullable=False),
        sa.Column("rationale", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["pair_id"],
            ["material_pairs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_tasks_pair_id"), "review_tasks", ["pair_id"], unique=False)
    op.create_index(op.f("ix_review_tasks_status"), "review_tasks", ["status"], unique=False)
    op.create_table(
        "material_attributes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("material_id", sa.String(length=80), nullable=False),
        sa.Column("attribute_name", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("normalized_value", sa.Text(), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("dimension", sa.String(length=50), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "material_id", "attribute_name", "normalized_value", name="uq_material_attribute"
        ),
    )
    op.create_index(
        op.f("ix_material_attributes_attribute_name"),
        "material_attributes",
        ["attribute_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_material_attributes_material_id"),
        "material_attributes",
        ["material_id"],
        unique=False,
    )
    op.create_table(
        "nmc_mappings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nmc", sa.String(length=100), nullable=False),
        sa.Column("cpse", sa.String(length=100), nullable=False),
        sa.Column("legacy_material_code", sa.String(length=200), nullable=False),
        sa.Column("plant", sa.String(length=200), nullable=False),
        sa.Column("source_system", sa.String(length=100), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mapping_status", sa.String(length=32), nullable=False),
        sa.Column("mapping_confidence", sa.Float(), nullable=True),
        sa.Column("approved_by", sa.String(length=200), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("review_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["nmc"],
            ["nmc_registry.nmc"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "nmc", "cpse", "legacy_material_code", "plant", name="uq_nmc_legacy_map"
        ),
    )
    op.create_index(op.f("ix_nmc_mappings_cpse"), "nmc_mappings", ["cpse"], unique=False)
    op.create_index(
        op.f("ix_nmc_mappings_legacy_material_code"),
        "nmc_mappings",
        ["legacy_material_code"],
        unique=False,
    )
    op.create_index(op.f("ix_nmc_mappings_nmc"), "nmc_mappings", ["nmc"], unique=False)
    op.create_table(
        "review_decisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("review_id", sa.String(length=80), nullable=False),
        sa.Column("reviewer_id", sa.String(length=200), nullable=False),
        sa.Column("reviewer_role", sa.String(length=40), nullable=False),
        sa.Column("relation", sa.String(length=60), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("checker_id", sa.String(length=200), nullable=False),
        sa.Column("checker_role", sa.String(length=40), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["review_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_decisions_review_id"), "review_decisions", ["review_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_decisions_review_id"), table_name="review_decisions")
    op.drop_table("review_decisions")
    op.drop_index(op.f("ix_nmc_mappings_nmc"), table_name="nmc_mappings")
    op.drop_index(op.f("ix_nmc_mappings_legacy_material_code"), table_name="nmc_mappings")
    op.drop_index(op.f("ix_nmc_mappings_cpse"), table_name="nmc_mappings")
    op.drop_table("nmc_mappings")
    op.drop_index(op.f("ix_material_attributes_material_id"), table_name="material_attributes")
    op.drop_index(op.f("ix_material_attributes_attribute_name"), table_name="material_attributes")
    op.drop_table("material_attributes")
    op.drop_index(op.f("ix_review_tasks_status"), table_name="review_tasks")
    op.drop_index(op.f("ix_review_tasks_pair_id"), table_name="review_tasks")
    op.drop_table("review_tasks")
    op.drop_index(op.f("ix_nmc_registry_family"), table_name="nmc_registry")
    op.drop_index(op.f("ix_nmc_registry_canonical_material_id"), table_name="nmc_registry")
    op.drop_table("nmc_registry")
    op.drop_index(op.f("ix_materials_source_artifact_id"), table_name="materials")
    op.drop_index(op.f("ix_materials_organization"), table_name="materials")
    op.drop_index(op.f("ix_materials_material_code"), table_name="materials")
    op.drop_table("materials")
    op.drop_index(op.f("ix_taxonomies_taxonomy_code"), table_name="taxonomies")
    op.drop_index(op.f("ix_taxonomies_taxonomy"), table_name="taxonomies")
    op.drop_table("taxonomies")
    op.drop_index(op.f("ix_source_artifacts_source_system"), table_name="source_artifacts")
    op.drop_table("source_artifacts")
    op.drop_table("model_versions")
    op.drop_index(op.f("ix_material_pairs_material_b"), table_name="material_pairs")
    op.drop_index(op.f("ix_material_pairs_material_a"), table_name="material_pairs")
    op.drop_table("material_pairs")
    op.drop_table("evaluation_runs")
    op.drop_index(op.f("ix_canonical_materials_family"), table_name="canonical_materials")
    op.drop_table("canonical_materials")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
