#!/usr/bin/env python3
"""
Build the reference vocabulary tables used to normalise CPSE material
descriptions:

  data/reference/abbreviations/material_abbreviations.csv
  data/reference/units/unit_normalisation.csv
  data/reference/abbreviations/material_grades.csv
  data/reference/abbreviations/pressure_classes.csv

Every row is written as (surface form -> canonical form) so the normaliser can
be a straight lookup, and each row records where the term came from so the
table is auditable.
"""
import csv
import os

ABBR_OUT = "data/reference/abbreviations/material_abbreviations.csv"
UNIT_OUT = "data/reference/units/unit_normalisation.csv"
GRADE_OUT = "data/reference/abbreviations/material_grades.csv"
CLASS_OUT = "data/reference/abbreviations/pressure_classes.csv"

# (surface_form, canonical_form, attribute, note)
ABBREV = [
    # ---- valves / valve types ----
    ("BALL VL", "BALL VALVE", "item_type", "CPSE shorthand seen in oil & gas catalogs"),
    ("BALL VLV", "BALL VALVE", "item_type", ""),
    ("BLV", "BALL VALVE", "item_type", ""),
    ("GATE VLV", "GATE VALVE", "item_type", ""),
    ("GATE VL", "GATE VALVE", "item_type", ""),
    ("GLB VLV", "GLOBE VALVE", "item_type", ""),
    ("GLOBE VL", "GLOBE VALVE", "item_type", ""),
    ("BFLY VLV", "BUTTERFLY VALVE", "item_type", ""),
    ("B/F VLV", "BUTTERFLY VALVE", "item_type", ""),
    ("BUTTERFLY VL", "BUTTERFLY VALVE", "item_type", ""),
    ("CHK VLV", "CHECK VALVE", "item_type", ""),
    ("NRV", "CHECK VALVE", "item_type", "non-return valve"),
    ("NON RETURN VALVE", "CHECK VALVE", "item_type", ""),
    ("CTRL VLV", "CONTROL VALVE", "item_type", ""),
    ("CV", "CONTROL VALVE", "item_type", "ambiguous: also control valve"),
    ("PSV", "PRESSURE SAFETY VALVE", "item_type", ""),
    ("PRV", "PRESSURE RELIEF VALVE", "item_type", ""),
    ("SAFETY VLV", "SAFETY VALVE", "item_type", ""),
    ("RELIEF VLV", "RELIEF VALVE", "item_type", ""),
    ("NDL VLV", "NEEDLE VALVE", "item_type", ""),
    ("PLUG VLV", "PLUG VALVE", "item_type", ""),
    ("DIA VLV", "DIAPHRAGM VALVE", "item_type", ""),
    ("VLV", "VALVE", "item_type", ""),
    ("VLVS", "VALVE", "item_type", ""),
    ("ACTR", "ACTUATOR", "component", ""),
    ("TRIM", "TRIM", "component", "valve internal parts"),
    # ---- pumps / rotating ----
    ("PMP", "PUMP", "item_type", ""),
    ("CNTRFGL PMP", "CENTRIFUGAL PUMP", "item_type", ""),
    ("CENT PUMP", "CENTRIFUGAL PUMP", "item_type", ""),
    ("RECIP PUMP", "RECIPROCATING PUMP", "item_type", ""),
    ("MECH SEAL", "MECHANICAL SEAL", "component", ""),
    ("M/S", "MECHANICAL SEAL", "component", "context dependent"),
    ("IMPL", "IMPELLER", "component", ""),
    ("BRG", "BEARING", "component", ""),
    ("BRG.", "BEARING", "component", ""),
    ("COMP", "COMPRESSOR", "item_type", ""),
    ("CMPR", "COMPRESSOR", "item_type", ""),
    ("GBX", "GEARBOX", "item_type", ""),
    ("G/B", "GEARBOX", "item_type", ""),
    ("CPLG", "COUPLING", "component", ""),
    ("HX", "HEAT EXCHANGER", "item_type", ""),
    ("AFC", "AIR FIN COOLER", "item_type", ""),
    ("FIN FAN COOLER", "AIR FIN COOLER", "item_type", ""),
    # ---- pipes / fittings / flanges ----
    ("PIPE FTG", "PIPE FITTING", "item_type", ""),
    ("FTG", "FITTING", "item_type", ""),
    ("FTGS", "FITTING", "item_type", ""),
    ("FLG", "FLANGE", "item_type", ""),
    ("FLGS", "FLANGE", "item_type", ""),
    ("WN", "WELD NECK", "end_connection", "weld neck flange"),
    ("SO", "SLIP ON", "end_connection", "slip-on flange"),
    ("BL", "BLIND", "end_connection", "blind flange"),
    ("LJ", "LAP JOINT", "end_connection", ""),
    ("SW", "SOCKET WELD", "end_connection", ""),
    ("BW", "BUTT WELD", "end_connection", ""),
    ("THD", "THREADED", "end_connection", ""),
    ("NPT", "NPT THREADED", "end_connection", "National Pipe Thread"),
    ("RF", "RAISED FACE", "end_connection", "flange facing"),
    ("FF", "FLAT FACE", "end_connection", "flange facing"),
    ("RTJ", "RING TYPE JOINT", "end_connection", "flange facing"),
    ("SMLS", "SEAMLESS", "manufacturing", ""),
    ("SEML", "SEAMLESS", "manufacturing", ""),
    ("ERW", "ELECTRIC RESISTANCE WELD", "manufacturing", ""),
    ("SAW", "SUBMERGED ARC WELD", "manufacturing", ""),
    ("LSAW", "LONGITUDINAL SUBMERGED ARC WELD", "manufacturing", ""),
    ("DSAW", "DOUBLE SUBMERGED ARC WELD", "manufacturing", ""),
    ("GASK", "GASKET", "item_type", ""),
    ("SWG", "SPIRAL WOUND GASKET", "item_type", ""),
    ("STUD BOLT", "STUD BOLT", "item_type", ""),
    # ---- materials ----
    ("CS", "CARBON STEEL", "material", ""),
    ("C.S.", "CARBON STEEL", "material", ""),
    ("CARB.STEEL", "CARBON STEEL", "material", ""),
    ("MS", "MILD STEEL", "material", ""),
    ("SS", "STAINLESS STEEL", "material", ""),
    ("S.S.", "STAINLESS STEEL", "material", ""),
    ("SS304", "STAINLESS STEEL 304", "material", ""),
    ("SS316", "STAINLESS STEEL 316", "material", ""),
    ("AS", "ALLOY STEEL", "material", ""),
    ("LTCS", "LOW TEMPERATURE CARBON STEEL", "material", ""),
    ("DUPLEX", "DUPLEX STAINLESS STEEL", "material", ""),
    ("GV", "GALVANISED", "material", ""),
    ("GI", "GALVANISED IRON", "material", ""),
    ("CI", "CAST IRON", "material", ""),
    ("DI", "DUCTILE IRON", "material", ""),
    ("WCB", "CAST CARBON STEEL WCB", "material_grade", "ASTM A216 Gr WCB"),
    ("WC6", "CAST ALLOY STEEL WC6", "material_grade", "ASTM A217 Gr WC6"),
    ("WC9", "CAST ALLOY STEEL WC9", "material_grade", "ASTM A217 Gr WC9"),
    ("CF8", "CAST STAINLESS STEEL CF8", "material_grade", "ASTM A351 CF8"),
    ("CF8M", "CAST STAINLESS STEEL CF8M", "material_grade", "ASTM A351 CF8M"),
    ("A105", "FORGED CARBON STEEL A105", "material_grade", "ASTM A105"),
    ("A182 F11", "FORGED ALLOY STEEL F11", "material_grade", "ASTM A182 F11"),
    ("A182 F22", "FORGED ALLOY STEEL F22", "material_grade", "ASTM A182 F22"),
    ("A182 F304", "FORGED STAINLESS STEEL F304", "material_grade", ""),
    ("A182 F316", "FORGED STAINLESS STEEL F316", "material_grade", ""),
    ("A106 GR B", "SEAMLESS CARBON STEEL PIPE A106 GR B", "material_grade", "ASTM A106"),
    ("A53 GR B", "CARBON STEEL PIPE A53 GR B", "material_grade", "ASTM A53"),
    ("A312 TP304", "STAINLESS STEEL PIPE A312 TP304", "material_grade", ""),
    ("A312 TP316", "STAINLESS STEEL PIPE A312 TP316", "material_grade", ""),
    ("A193 B7", "ALLOY STEEL STUD BOLT B7", "material_grade", "ASTM A193 B7"),
    ("A194 2H", "CARBON STEEL NUT 2H", "material_grade", "ASTM A194 2H"),
    ("API 5L", "API 5L LINE PIPE", "material_grade", ""),
    ("IS 1239", "IS 1239 STEEL TUBE", "material_grade", "Indian Standard"),
    ("IS 3589", "IS 3589 ERW STEEL TUBE", "material_grade", ""),
    # ---- electrical / instrumentation ----
    ("XMER", "TRANSFORMER", "item_type", ""),
    ("TRF", "TRANSFORMER", "item_type", ""),
    ("TX", "TRANSFORMER", "item_type", "context dependent"),
    ("VCB", "VACUUM CIRCUIT BREAKER", "item_type", ""),
    ("SF6 CB", "SF6 CIRCUIT BREAKER", "item_type", ""),
    ("ACB", "AIR CIRCUIT BREAKER", "item_type", ""),
    ("MCCB", "MOULDED CASE CIRCUIT BREAKER", "item_type", ""),
    ("MCB", "MINIATURE CIRCUIT BREAKER", "item_type", ""),
    ("CT", "CURRENT TRANSFORMER", "item_type", ""),
    ("PT", "POTENTIAL TRANSFORMER", "item_type", ""),
    ("LA", "LIGHTNING ARRESTER", "item_type", ""),
    ("VFD", "VARIABLE FREQUENCY DRIVE", "item_type", ""),
    ("XLPE", "CROSS LINKED POLYETHYLENE CABLE", "material", ""),
    ("PILC", "PAPER INSULATED LEAD COVERED CABLE", "material", ""),
    ("PG", "PRESSURE GAUGE", "item_type", ""),
    ("TT", "TEMPERATURE TRANSMITTER", "item_type", ""),
    ("PTX", "PRESSURE TRANSMITTER", "item_type", ""),
    ("LT", "LEVEL TRANSMITTER", "item_type", ""),
    ("FT", "FLOW TRANSMITTER", "item_type", ""),
    ("TC", "THERMOCOUPLE", "item_type", ""),
    ("RTD", "RESISTANCE TEMPERATURE DETECTOR", "item_type", ""),
    ("PT100", "PLATINUM RTD PT100", "item_type", ""),
    ("ORF", "ORIFICE", "item_type", ""),
    ("PLC", "PROGRAMMABLE LOGIC CONTROLLER", "item_type", ""),
    ("DCS", "DISTRIBUTED CONTROL SYSTEM", "item_type", ""),
    ("ESD", "EMERGENCY SHUTDOWN SYSTEM", "item_type", ""),
    # ---- procurement vocabulary (seen in the harvested NTPC corpus) ----
    ("AMC", "ANNUAL MAINTENANCE CONTRACT", "contract_type", ""),
    ("O&M", "OPERATION AND MAINTENANCE", "contract_type", ""),
    ("EPC", "ENGINEERING PROCUREMENT CONSTRUCTION", "contract_type", ""),
    ("NIT", "NOTICE INVITING TENDER", "document_type", ""),
    ("BOQ", "BILL OF QUANTITIES", "document_type", ""),
    ("EMD", "EARNEST MONEY DEPOSIT", "commercial", ""),
    ("EOI", "EXPRESSION OF INTEREST", "document_type", ""),
    ("RFQ", "REQUEST FOR QUOTATION", "document_type", ""),
    ("PO", "PURCHASE ORDER", "document_type", ""),
    ("GTC", "GENERAL TERMS AND CONDITIONS", "document_type", ""),
    ("SPARES", "SPARE PARTS", "item_class", ""),
    ("SP", "SPARE PARTS", "item_class", ""),
    ("CAPITAL SPARES", "CAPITAL SPARE PARTS", "item_class", ""),
    ("MISC", "MISCELLANEOUS", "item_class", ""),
    ("MTS", "MADE TO SPECIFICATION", "sourcing", ""),
    ("MTD", "MADE TO DIMENSION", "sourcing", ""),
    ("STD", "STANDARD", "sourcing", ""),
    ("WGC", "WORK GROUP", "organisation", ""),
    ("CHP", "COAL HANDLING PLANT", "plant_area", "seen in NTPC corpus"),
    ("AHP", "ASH HANDLING PLANT", "plant_area", "seen in NTPC corpus"),
    ("STPP", "SUPER THERMAL POWER PROJECT", "plant_area", "seen in NTPC corpus"),
    ("TPD", "TONNES PER DAY", "capacity_unit", ""),
    ("TPH", "TONNES PER HOUR", "capacity_unit", ""),
    ("FGD", "FLUE GAS DESULPHURISATION", "plant_area", "seen in NTPC corpus"),
    ("ESP", "ELECTROSTATIC PRECIPITATOR", "plant_area", "seen in NTPC corpus"),
    ("BESS", "BATTERY ENERGY STORAGE SYSTEM", "item_type", "seen in NTPC corpus"),
]

# (surface_form, canonical_unit, quantity, factor_to_canonical, note)
UNITS = [
    # each / number
    ("EA", "NOS", "count", 1, ""),
    ("EACH", "NOS", "count", 1, ""),
    ("NO", "NOS", "count", 1, ""),
    ("NO.", "NOS", "count", 1, ""),
    ("NOS", "NOS", "count", 1, ""),
    ("NOS.", "NOS", "count", 1, ""),
    ("NUM", "NOS", "count", 1, ""),
    ("NUMBER", "NOS", "count", 1, ""),
    ("NUMBERS", "NOS", "count", 1, ""),
    ("PC", "NOS", "count", 1, ""),
    ("PCS", "NOS", "count", 1, ""),
    ("PIECE", "NOS", "count", 1, ""),
    ("PIECES", "NOS", "count", 1, ""),
    ("SET", "SET", "count", 1, ""),
    ("SETS", "SET", "count", 1, ""),
    ("PAIR", "PAIR", "count", 1, ""),
    ("PAIRS", "PAIR", "count", 1, ""),
    ("LOT", "LOT", "count", 1, ""),
    ("LOTS", "LOT", "count", 1, ""),
    ("PKG", "PACKAGE", "count", 1, ""),
    ("PACKAGE", "PACKAGE", "count", 1, ""),
    ("ASSORTED", "LOT", "count", 1, "common in IOCL plan"),
    ("ITEM", "NOS", "count", 1, ""),
    ("UNIT", "NOS", "count", 1, ""),
    ("UNITS", "NOS", "count", 1, ""),
    # length
    ("MM", "MM", "length", 1, ""),
    ("MMS", "MM", "length", 1, ""),
    ("MILLIMETER", "MM", "length", 1, ""),
    ("MILLIMETRE", "MM", "length", 1, ""),
    ("CM", "MM", "length", 10, ""),
    ("CENTIMETER", "MM", "length", 10, ""),
    ("M", "M", "length", 1, ""),
    ("MTR", "M", "length", 1, ""),
    ("MTRS", "M", "length", 1, ""),
    ("METER", "M", "length", 1, ""),
    ("METRE", "M", "length", 1, ""),
    ("METERS", "M", "length", 1, ""),
    ("KM", "KM", "length", 1, ""),
    ("KMS", "KM", "length", 1, ""),
    ("KILOMETER", "KM", "length", 1, ""),
    ("IN", "INCH", "length", 1, "size in inches"),
    ("IN.", "INCH", "length", 1, ""),
    ("INCH", "INCH", "length", 1, ""),
    ("INCHES", "INCH", "length", 1, ""),
    ('"', "INCH", "length", 1, "double-quote notation e.g. 4\""),
    ("NB", "MM", "length", 1, "nominal bore, stated in mm"),
    ("DN", "MM", "length", 1, "diametre nominal, stated in mm"),
    # inch <-> mm size equivalences used in valve/pipe specs
    ("1/2 INCH", "15 MM", "size_equivalence", 1, ""),
    ("3/4 INCH", "20 MM", "size_equivalence", 1, ""),
    ("1 INCH", "25 MM", "size_equivalence", 1, ""),
    ("1-1/2 INCH", "40 MM", "size_equivalence", 1, ""),
    ("1 1/2 INCH", "40 MM", "size_equivalence", 1, ""),
    ("2 INCH", "50 MM", "size_equivalence", 1, ""),
    ("3 INCH", "80 MM", "size_equivalence", 1, ""),
    ("4 INCH", "100 MM", "size_equivalence", 1, ""),
    ("6 INCH", "150 MM", "size_equivalence", 1, ""),
    ("8 INCH", "200 MM", "size_equivalence", 1, ""),
    ("10 INCH", "250 MM", "size_equivalence", 1, ""),
    ("12 INCH", "300 MM", "size_equivalence", 1, ""),
    ("14 INCH", "350 MM", "size_equivalence", 1, ""),
    ("16 INCH", "400 MM", "size_equivalence", 1, ""),
    ("18 INCH", "450 MM", "size_equivalence", 1, ""),
    ("20 INCH", "500 MM", "size_equivalence", 1, ""),
    ("24 INCH", "600 MM", "size_equivalence", 1, ""),
    # mass
    ("KG", "KG", "mass", 1, ""),
    ("KGS", "KG", "mass", 1, ""),
    ("KILOGRAM", "KG", "mass", 1, ""),
    ("KILOGRAMS", "KG", "mass", 1, ""),
    ("GM", "KG", "mass", 0.001, ""),
    ("GRAM", "KG", "mass", 0.001, ""),
    ("GRAMS", "KG", "mass", 0.001, ""),
    ("MT", "MT", "mass", 1, ""),
    ("MTS", "MT", "mass", 1, "metric tonnes"),
    ("TON", "MT", "mass", 1, ""),
    ("TONS", "MT", "mass", 1, ""),
    ("TONNE", "MT", "mass", 1, ""),
    ("TONNES", "MT", "mass", 1, ""),
    ("LMT", "MT", "mass", 100000, "lakh metric tonnes, seen in NTPC corpus"),
    # volume
    ("LTR", "L", "volume", 1, ""),
    ("LTRS", "L", "volume", 1, ""),
    ("LITRE", "L", "volume", 1, ""),
    ("LITRES", "L", "volume", 1, ""),
    ("LITER", "L", "volume", 1, ""),
    ("LITERS", "L", "volume", 1, ""),
    ("KL", "KL", "volume", 1, ""),
    ("KLS", "KL", "volume", 1, "seen in OIL India corpus"),
    ("CUM", "M3", "volume", 1, ""),
    ("M3", "M3", "volume", 1, ""),
    ("CBM", "M3", "volume", 1, ""),
    # area
    ("SQM", "M2", "area", 1, ""),
    ("SQ.M", "M2", "area", 1, ""),
    ("M2", "M2", "area", 1, ""),
    ("SQFT", "FT2", "area", 1, ""),
    # power / electrical
    ("KW", "KW", "power", 1, ""),
    ("KWS", "KW", "power", 1, ""),
    ("MEGAWATT", "KW", "power", 1000, ""),
    ("MW", "MW", "power", 1, "seen in NTPC corpus"),
    ("HP", "KW", "power", 0.7457, ""),
    ("KV", "KV", "voltage", 1, "seen in NTPC corpus"),
    ("V", "V", "voltage", 1, ""),
    ("AMP", "A", "current", 1, ""),
    ("AMPS", "A", "current", 1, ""),
    ("KVA", "KVA", "apparent_power", 1, ""),
    ("MVA", "MVA", "apparent_power", 1, ""),
    # pressure
    ("BAR", "BAR", "pressure", 1, ""),
    ("BARS", "BAR", "pressure", 1, ""),
    ("KG/CM2", "BAR", "pressure", 0.980665, ""),
    ("KGCM2", "BAR", "pressure", 0.980665, ""),
    ("MPA", "BAR", "pressure", 10, ""),
    ("KPA", "BAR", "pressure", 0.01, ""),
    ("PSI", "BAR", "pressure", 0.0689476, ""),
    ("PSIG", "BAR", "pressure", 0.0689476, ""),
    # time / service
    ("MONTH", "MONTH", "duration", 1, ""),
    ("MONTHS", "MONTH", "duration", 1, ""),
    ("MTH", "MONTH", "duration", 1, ""),
    ("YEAR", "YEAR", "duration", 1, ""),
    ("YEARS", "YEAR", "duration", 1, ""),
    ("YR", "YEAR", "duration", 1, ""),
    ("HOUR", "HOUR", "duration", 1, ""),
    ("HOURS", "HOUR", "duration", 1, ""),
    ("HR", "HOUR", "duration", 1, ""),
    ("HRS", "HOUR", "duration", 1, ""),
    ("DAY", "DAY", "duration", 1, ""),
    ("DAYS", "DAY", "duration", 1, ""),
    ("SHIFT", "SHIFT", "duration", 1, ""),
]

GRADES = [
    ("WCB", "ASTM A216", "WCB", "cast carbon steel", "valve/flange bodies"),
    ("WCC", "ASTM A216", "WCC", "cast carbon steel", ""),
    ("WC6", "ASTM A217", "WC6", "cast 1.25Cr-0.5Mo alloy steel", ""),
    ("WC9", "ASTM A217", "WC9", "cast 2.25Cr-1Mo alloy steel", ""),
    ("C5", "ASTM A217", "C5", "cast 5Cr-0.5Mo", ""),
    ("CF8", "ASTM A351", "CF8", "cast 18Cr-8Ni stainless", "equiv. 304"),
    ("CF8M", "ASTM A351", "CF8M", "cast 18Cr-10Ni-Mo stainless", "equiv. 316"),
    ("CF3", "ASTM A351", "CF3", "cast low-carbon 304L", ""),
    ("CF3M", "ASTM A351", "CF3M", "cast low-carbon 316L", ""),
    ("A105", "ASTM A105", "A105", "forged carbon steel", "flanges/fittings"),
    ("A182 F5", "ASTM A182", "F5", "forged 5Cr", ""),
    ("A182 F9", "ASTM A182", "F9", "forged 9Cr", ""),
    ("A182 F11", "ASTM A182", "F11", "forged 1.25Cr-0.5Mo", ""),
    ("A182 F22", "ASTM A182", "F22", "forged 2.25Cr-1Mo", ""),
    ("A182 F304", "ASTM A182", "F304", "forged 304 stainless", ""),
    ("A182 F304L", "ASTM A182", "F304L", "forged 304L stainless", ""),
    ("A182 F316", "ASTM A182", "F316", "forged 316 stainless", ""),
    ("A182 F316L", "ASTM A182", "F316L", "forged 316L stainless", ""),
    ("A182 F51", "ASTM A182", "F51", "forged duplex 2205", ""),
    ("A106 GR A", "ASTM A106", "GR A", "seamless carbon steel pipe", ""),
    ("A106 GR B", "ASTM A106", "GR B", "seamless carbon steel pipe", "most common"),
    ("A106 GR C", "ASTM A106", "GR C", "seamless carbon steel pipe", ""),
    ("A53 GR A", "ASTM A53", "GR A", "carbon steel pipe", ""),
    ("A53 GR B", "ASTM A53", "GR B", "carbon steel pipe", ""),
    ("A333 GR 6", "ASTM A333", "GR 6", "low temperature carbon steel pipe", "LTCS"),
    ("A335 P11", "ASTM A335", "P11", "alloy steel seamless pipe", ""),
    ("A335 P22", "ASTM A335", "P22", "alloy steel seamless pipe", ""),
    ("A312 TP304", "ASTM A312", "TP304", "stainless seamless pipe", ""),
    ("A312 TP316", "ASTM A312", "TP316", "stainless seamless pipe", ""),
    ("A312 TP316L", "ASTM A312", "TP316L", "stainless seamless pipe", ""),
    ("A234 WPB", "ASTM A234", "WPB", "carbon steel butt-weld fitting", ""),
    ("A234 WP11", "ASTM A234", "WP11", "alloy steel butt-weld fitting", ""),
    ("A234 WP22", "ASTM A234", "WP22", "alloy steel butt-weld fitting", ""),
    ("A403 WP304", "ASTM A403", "WP304", "stainless butt-weld fitting", ""),
    ("A403 WP316", "ASTM A403", "WP316", "stainless butt-weld fitting", ""),
    ("A193 B7", "ASTM A193", "B7", "alloy steel bolting", "stud bolts"),
    ("A193 B8", "ASTM A193", "B8", "304 stainless bolting", ""),
    ("A193 B8M", "ASTM A193", "B8M", "316 stainless bolting", ""),
    ("A194 GR 2H", "ASTM A194", "2H", "carbon steel nut", ""),
    ("A194 GR 8", "ASTM A194", "8", "304 stainless nut", ""),
    ("API 5L GR B", "API 5L", "GR B", "line pipe", ""),
    ("API 5L X42", "API 5L", "X42", "line pipe", ""),
    ("API 5L X52", "API 5L", "X52", "line pipe", ""),
    ("API 5L X60", "API 5L", "X60", "line pipe", ""),
    ("API 5L X65", "API 5L", "X65", "line pipe", ""),
    ("API 5L X70", "API 5L", "X70", "line pipe", ""),
    ("API 6D", "API 6D", "-", "pipeline valves specification", ""),
    ("API 600", "API 600", "-", "bolted bonnet steel gate valves", ""),
    ("API 602", "API 602", "-", "compact steel gate/globe/check valves", ""),
    ("API 608", "API 608", "-", "metal ball valves", ""),
    ("API 609", "API 609", "-", "butterfly valves", ""),
    ("ASME B16.5", "ASME B16.5", "-", "pipe flanges and flanged fittings", ""),
    ("ASME B16.9", "ASME B16.9", "-", "factory-made butt-welding fittings", ""),
    ("ASME B16.11", "ASME B16.11", "-", "forged fittings, socket-welding/threaded", ""),
    ("ASME B16.20", "ASME B16.20", "-", "metallic gaskets for pipe flanges", ""),
    ("IS 1239", "IS 1239", "-", "Indian Standard steel tubes", ""),
    ("IS 3589", "IS 3589", "-", "Indian Standard ERW steel tubes", ""),
    ("IS 6527", "IS 6527", "-", "Indian Standard steel wire ropes", ""),
]

CLASSES = [
    ("150", "CLASS 150", "PN20", "ASME B16.5 Class 150"),
    ("150#", "CLASS 150", "PN20", "hash notation"),
    ("CL 150", "CLASS 150", "PN20", ""),
    ("CLASS150", "CLASS 150", "PN20", ""),
    ("300", "CLASS 300", "PN50", ""),
    ("300#", "CLASS 300", "PN50", "hash notation, e.g. 'BALL VALVE 4\" CS 300#'"),
    ("CL 300", "CLASS 300", "PN50", ""),
    ("CL300", "CLASS 300", "PN50", ""),
    ("CLASS-300", "CLASS 300", "PN50", "hyphenated form seen in BPCL-style text"),
    ("CLASS 300", "CLASS 300", "PN50", ""),
    ("600", "CLASS 600", "PN100", ""),
    ("600#", "CLASS 600", "PN100", ""),
    ("CL 600", "CLASS 600", "PN100", ""),
    ("900", "CLASS 900", "PN150", ""),
    ("CL 900", "CLASS 900", "PN150", ""),
    ("1500", "CLASS 1500", "PN250", ""),
    ("CL 1500", "CLASS 1500", "PN250", ""),
    ("2500", "CLASS 2500", "PN420", ""),
    ("PN6", "PN6", "CLASS 150", ""),
    ("PN10", "PN10", "CLASS 150", ""),
    ("PN16", "PN16", "CLASS 150", ""),
    ("PN25", "PN25", "CLASS 300", ""),
    ("PN40", "PN40", "CLASS 300", ""),
    ("PN64", "PN64", "CLASS 600", ""),
    ("PN100", "PN100", "CLASS 600", ""),
    ("PN160", "PN160", "CLASS 900", ""),
    ("PN250", "PN250", "CLASS 1500", ""),
    ("PN420", "PN420", "CLASS 2500", ""),
]


def main():
    for p in (ABBR_OUT, UNIT_OUT, GRADE_OUT, CLASS_OUT):
        os.makedirs(os.path.dirname(p), exist_ok=True)

    with open(ABBR_OUT, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["surface_form", "canonical_form", "attribute", "note"])
        w.writerows(ABBREV)
    with open(UNIT_OUT, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["surface_form", "canonical_unit", "quantity",
                    "factor_to_canonical", "note"])
        w.writerows(UNITS)
    with open(GRADE_OUT, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["grade_token", "standard", "grade", "description", "note"])
        w.writerows(GRADES)
    with open(CLASS_OUT, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["surface_form", "asme_class", "approx_pn", "note"])
        w.writerows(CLASSES)

    print(f"abbreviations : {len(ABBREV)} -> {ABBR_OUT}")
    print(f"units         : {len(UNITS)} -> {UNIT_OUT}")
    print(f"grades        : {len(GRADES)} -> {GRADE_OUT}")
    print(f"pressure cls  : {len(CLASSES)} -> {CLASS_OUT}")


if __name__ == "__main__":
    main()
